Vagrant.require_version ">= 2.1.0"
Vagrant.configure("2") do |config|
	config.vm.define "devops-vb" do |devbox|
		devbox.vm.box = "ubuntu/xenial64"
		#devbox.vm.network "private_network", ip: "192.168.199.9"
		devbox.vm.hostname = "devops-vb"
		devbox.vm.provision "shell", path: "scripts/install.sh"
		devbox.vm.provider "virtualbox" do |vb|
			vb.memory = 2048
			vb.cpus = 2
			vb.name = "devops-vb"
		end
	end
end
